### ISSUE TITLE
Rotating 90 degrees doesn't appropriate adjust outline.

### ISSUE THREAD

**Issue by tjlanza** [Ourobor/Hex-Size-Support#5]
When rotating a token's facing using SHIFT+Arrow, it does not maintain alignment with the grid when turning 90 degrees off the original axis. While this won't be a problem in systems with rigidly defined facing rules, in less particular games can allow non-60-degree facings.

![90 degrees](https://user-images.githubusercontent.com/21128724/98760726-e1353700-23a1-11eb-98d9-c0b18af721df.PNG)

**Comment by Ourobor** [comment]
Shift+Arrow key sets the tokens rotation to a specific value(0°,90°,180°, or 270°) based on the arrow direction which rotates both the art and border. I'm not sure what you need in regards to this. Are you asking to rotate the art but not the border, or that the shift+arrow should snap to a valid rotation?

Also, CTRL+Scroll will allow you to rotate the token in 15° increments which will allow you to change its facing to each of the 6 valid facings that align to the grid

**Comment by tjlanza** [comment]
It should rotate the art without rotating the border - the border should always align to the grid.

**Comment by Ourobor** [comment]
Oh, I see!
Apologies, it was set up that way because size 2/4 tokens needed to have some way to reorient themselves to align with the other snap locations. I'll make a note to relock the border-rotation once I add in a new keybind to flip the border for those size tokens.
Thanks, would probably totally have forgotten this otherwise

**Comment by Ourobor** [comment]
This should now be resolved with the newest version of the module. I haven't gotten around to updating the readme, but shift+r flips the border and rotating the token only rotates the art now.
